class AssetOwnImages {
  static const String path = "assets/icons",
      logo = "$path/arte_logo-02.png",
      github = "$path/github.png",
      facebook = "$path/facebook.png",
      linkedin = "$path/link.png",
      livein = "$path/livein.png",
      mobile = "$path/mobile.png",
      tel = "$path/tel.png",
      liveinSvg = "$path/livein.svg",
      mobileSvg = "$path/mobile.svg",
      telSvg = "$path/tel.svg",
      githubSvg = "$path/github.svg",
      facebookSvg = "$path/facebook.svg",
      linkedinSvg = "$path/link.svg",
      wib = "$path/wib.png",
      btq = "$path/btq.png",
      playstoreSvg = "$path/playstore.svg",
      playstore = "$path/playstore.png",
      appstoreSvg = "$path/appstore.svg",
      appstore = "$path/appstore.png",
      pets = "$path/pets.png",
      shopal = "$path/shopal.png",
      appDev = "$path/appdev.png",
      uiux = "$path/uiux.png",
      menu = "$path/menu.png";
}
